from django.contrib import admin
from .models import *

admin.site.register(ObjectRegister)
admin.site.register(OtherNumber)
admin.site.register(ObjectName)
admin.site.register(Production)
admin.site.register(AgentRole)
admin.site.register(ObjectPlaceType)
admin.site.register(ObjectUnit)
admin.site.register(Specimen)
admin.site.register(Artifact)
admin.site.register(WorkInstance)
admin.site.register(Dimension)
admin.site.register(Inscription)
admin.site.register(TechnicalAttribute)
admin.site.register(Colour)
admin.site.register(SpecimenDateType)
admin.site.register(ArtifactDateType)
admin.site.register(Material)
admin.site.register(MaterialType)
admin.site.register(DescriptionContent)
admin.site.register(ContentMeta)
admin.site.register(Rights)
admin.site.register(AssociatedObject)
admin.site.register(Ownership)
admin.site.register(Hierarchy)
admin.site.register(RelatedObject)
admin.site.register(TextRef)
admin.site.register(IsoLanguage)
