from django.contrib import admin
from .models import *

admin.site.register(ObjectIdentification)
admin.site.register(OtherObjectNumber)
admin.site.register(ObjectName)
admin.site.register(ObjectProduction)
admin.site.register(AgentRole)
admin.site.register(ObjectPlaceType)
admin.site.register(TechniqueType)
admin.site.register(ObjectUnit)
admin.site.register(Specimen)
admin.site.register(Artifact)
admin.site.register(WorkInstance)
admin.site.register(ObjectDimension)
admin.site.register(ObjectInscription)
admin.site.register(TechnicalAttribute)
admin.site.register(Colour)
admin.site.register(SpecimenDateType)
admin.site.register(ArtifactDateType)
admin.site.register(ObjectMaterial)
admin.site.register(MaterialType)
admin.site.register(DescriptionContent)
admin.site.register(ContentMeta)
admin.site.register(ObjectRights)
admin.site.register(AssociatedObject)
admin.site.register(Ownership)
admin.site.register(ObjectHierarchy)
admin.site.register(RelatedObject)
admin.site.register(TextRef)
admin.site.register(IsoLanguage)
